INSERT INTO Product
VALUES('A',1001,'PC');
INSERT INTO Product
VALUES('A',1002,'PC');
INSERT INTO Product
VALUES('A',1003,'PC');
INSERT INTO Product
VALUES('A',2004,'LAPTOP');
INSERT INTO Product
VALUES('A',2005,'LAPTOP');
INSERT INTO Product
VALUES('A',2006,'LAPTOP');
INSERT INTO Product
VALUES('B',1004,'PC');
INSERT INTO Product
VALUES('B',1005,'PC');
INSERT INTO Product
VALUES('B',1006,'PC');
INSERT INTO Product
VALUES('B',2001,'LAPTOP');
INSERT INTO Product
VALUES('B',2002,'LAPTOP');
INSERT INTO Product
VALUES('B',2003,'LAPTOP');
INSERT INTO Product
VALUES('C',1007,'PC');
INSERT INTO Product
VALUES('C',1008,'PC');
INSERT INTO Product
VALUES('C',2008,'LAPTOP');
INSERT INTO Product
VALUES('C',2009,'LAPTOP');
INSERT INTO Product
VALUES('C',3002,'PRINTER');
INSERT INTO Product
VALUES('C',3003,'PRINTER');
INSERT INTO Product
VALUES('C',3006,'PRINTER');
INSERT INTO Product
VALUES('D',1009,'PC');
INSERT INTO Product
VALUES('D',1010,'PC');
INSERT INTO Product
VALUES('D',1011,'PC');
INSERT INTO Product
VALUES('D',2007,'LAPTOP');
INSERT INTO Product
VALUES('E',1012,'PC');
INSERT INTO Product
VALUES('E',1013,'PC');
INSERT INTO Product
VALUES('E',2010,'LAPTOP');
INSERT INTO Product
VALUES('F',3001,'PRINTER');
INSERT INTO Product
VALUES('F',3004,'PRINTER');
INSERT INTO Product
VALUES('G',3005,'PRINTER');
INSERT INTO Product
VALUES('H',3007,'PRINTER');